trigger:
- master

pr: none

jobs:
- job: build_webappWithTests
  steps:
  - template: templates/build-dotnet-app.yml
    parameters:
      solutionRootPath: 'dotnet/aspnetcore31/webappWithTests/Application'

- job: build_webAppOnLinux
  steps:
  - template: templates/build-dotnet-app.yml
    parameters:
      solutionRootPath: 'dotnet/aspnetcore31/webAppOnLinux/Application'
   
