parameters:
  environment: ''
  appServicePlanName: '$(AppServicePlanName)'
  webAppName: '$(WebAppName)'
  azureConnectionName: 'azure-objectivity-msdn-a'
  subscriptionId: '$(SubscriptionId)'
  resourceGroupName: '$(ResourceGroupName)'
  location: 'North Europe'
  sku: 'F1'

resources:
  pipelines:
  - pipeline: BuildApp
    source: 'Build app with tasks'

jobs:
- deployment: deploy
  displayName: 'Deploy app on ${{ parameters.environment }}'
  environment: ${{ parameters.environment }}
  variables:
  - group: ms-common
  - group: ms-${{ parameters.environment }}
  strategy:
    runOnce:
      preDeploy:
        steps:
        - download: BuildApp
        - task: AzureResourceManagerTemplateDeployment@3
          inputs:
            deploymentScope: 'Resource Group'
            azureResourceManagerConnection: '${{ parameters.azureConnectionName }}'
            subscriptionId: '${{ parameters.subscriptionId }}'
            action: 'Create Or Update Resource Group'
            resourceGroupName: '${{ parameters.resourceGroupName }}'
            location: '${{ parameters.location }}'
            csmFile: '$(Pipeline.Workspace)/**/arm/*.json'
            overrideParameters: '-webAppName ${{ parameters.webAppName }} -hostingPlanName ${{ parameters.appServicePlanName }} -appInsightsLocation "NorthEurope" -sku ${{ parameters.sku }}'
      deploy:
        steps:
        - download: current
        - task: AzureRmWebAppDeployment@4
          displayName: 'Deploy Azure App Service'
          inputs:
            ConnectionType: 'AzureRM'
            azureSubscription: '${{ parameters.azureConnectionName }}'
            appType: 'webAppLinux'
            WebAppName: '${{ parameters.webAppName }}'
            packageForLinux: '$(Pipeline.Workspace)/**/*.zip'
            
      on:
        failure:
          steps:
          - script: 'curl https://maker.ifttt.com/trigger/deployment_failed/with/key/$(MakerKey)'
        success:
          steps:
          - script: 'curl https://maker.ifttt.com/trigger/deployment_success/with/key/$(MakerKey)'